export default [
  'chestnut',
  'Arctic blue',
  'amber',
  'aquamarine',
  'ash gray',
  'azure',
  'brandy',
  'cerulean',
  'chocolate brown',
  'chrome',
  'coal',
  'cocoa brown',
  'coffee brown',
  'cognac',
  'concrete gray',
  'copper',
  'cornflower blue',
  'crystal blue',
  'denim blue',
  'dove gray',
  'electric blue',
  'emerald',
  'fog gray',
  'glacial blue',
  'gunmetal gray',
  'hazel',
  'honey',
  'ice blue',
  'lake blue',
  'leaf green',
  'mahogany',
  'midnight',
  'mink brown',
  'mocha',
  'moss green',
  'obsidian',
  'olive',
  'onyx',
  'pewter',
  'platinum',
  'raven',
  'sepia',
  'shark gray',
  'sienna brown',
  'silver / silver gray',
  'sky blue',
  'slate blue / slate gray',
  'smoky gray',
  'steel blue',
  'storm blue / storm gray',
  'sunny blue',
  'tawny',
  'topaz',
  'turquoise',
  'whiskey'
];
