export default [
  'angular cheekbones',
  'broad forehead',
  'catlike',
  'chiseled',
  'cleft chin',
  'craggy',
  'dimple in chin',
  'double chin',
  'elongated',
  'heart-shaped',
  'high cheekbones',
  'high forehead',
  'hollow cheeks',
  'jowly',
  'jutting chin',
  'narrow',
  'oblong',
  'oval',
  'pointed chin',
  'prominent brow ridge',
  'protruding brow bone',
  'receding chin',
  'round',
  'sculpted',
  'sharp cheekbones',
  'soft',
  'square',
  'square jaw',
  'visible Adam’s apple',
  'weak chin',
  'wolfish'
];
