export default [
  'Black',
  'Beige',
  'Brown',
  'Fawn - light yellow-brown',
  'Gold - deep',
  'Khaki - dull',
  'Ochre - brownish-yellow',
  'Pale',
  'Pink',
  'Russet - reddish-brown',
  'Sepia - reddish-brown',
  'Taupe - grey',
  'Tawny - orange-yellowy-brown',
  'Terra-cotta - brownish-orange',
  'Umber - dark',
  'White',
  'brownish-yellow',
  'tinge of brown',
  'yellow-brown',
  'yellow-brown'
];
