export default {
  Black: [
    'Coal',
    'Crows wing',
    'Ebony',
    'Indian Ink',
    'Jet',
    'Midnight',
    'Obsidian',
    'Onyx',
    'Raven'
  ],
  'Grays and Whites': [
    'Battleship gray',
    'Blue dandelion fuzz',
    'Blue rinse gray',
    'Faded glory',
    'Flint',
    'Grizzled (gray)',
    'Gunmetal',
    'Maltese gray (blue gray)',
    'Mineral',
    'Mousy (gray)',
    'Pewter',
    'Salt and Pepper',
    'Shale',
    'Silver cloud',
    'Smoke',
    'Snowy white',
    'Steel',
    'Swan’s wing',
    'Wood ashes',
    'dull gray'
  ],
  Brown: [
    'Amber (reddish)',
    'Ash brown',
    'Auburn (reddish)',
    'Baked Clay',
    'Bison',
    'Brunette',
    'Burnished',
    'Camel',
    'Caramel',
    'Chestnut',
    'Cinnamon',
    'Clove',
    'Dark beer',
    'Dark Earth',
    'Dark toffee',
    'Dirt',
    'Fudge cycle',
    'Glazed ginger',
    'Maple Sugar',
    'Mink',
    'Mousy',
    'Muddy',
    'Nutmeg',
    'Pecan',
    'Rawhide, dark reddish',
    'Root beer',
    'Russet',
    'Tobacco',
    'Tortoise Shell',
    'Walnut'
  ],
  Reds: [
    'Auburn',
    'Berry',
    'Brassy',
    'Brightest',
    'Burgundy',
    'Burnished copper',
    'Carrot top',
    'Cinnabar',
    'Clown wig red',
    'Cognac',
    'Dull brick',
    'Flame',
    'Garish brass',
    'Orange',
    'Russet',
    'Scarlet',
    'Strawberry',
    'Wine'
  ]
};
