export default [
  'abuse',
  'age',
  'aged',
  'aging',
  'ago',
  'all timeback',
  'all-time',
  'ancient',
  'anteceding',
  'archival',
  'aristocratic',
  'at the dateplot',
  'attested',
  'audited',
  'authentic',
  'background',
  'before',
  'beginning',
  'budgeted',
  'bygone',
  'case history',
  'cataloged',
  'certain',
  'checked',
  'childhood',
  'chronicled',
  'chronologic',
  'chronological',
  'classic',
  'classical',
  'collected',
  'college',
  'counted',
  'custom',
  'dated',
  'death',
  'demonstrable',
  'demonstratable',
  'demonstrated',
  'depression',
  'detailed',
  'diachronic',
  'divorce',
  'documentary',
  'documented',
  'earlier periods',
  'earlier',
  'enumerated',
  'epoch-making',
  'epochal',
  'ever',
  'existent',
  'factual',
  'family',
  'filed',
  'first ever position',
  'previous periods',
  'the story',
  'former',
  'friendship',
  'history',
  'past experience',
  'the past',
  'genetic',
  'genuine',
  'gone',
  'grief',
  'has historically',
  'have historically',
  'heiroglyphics',
  'heredity',
  'historian',
  'historians',
  'historic',
  'historical narrative',
  'historical site',
  'historically',
  'historied',
  'histories',
  'historique',
  'history',
  'history-making',
  'humanistic discipline',
  'humanities',
  'immigrant',
  'immigration',
  'in history',
  'in human history',
  'in its history',
  'in the entire history',
  'in the history',
  'in the storyancient',
  'in the whole historydate',
  'indexed',
  'inventoried',
  'invoiced',
  'itemized',
  'journaled',
  'king',
  'kings',
  'land mark',
  'landmark',
  'last',
  'legendary',
  'liberal arts',
  'listed',
  'logged',
  'loss',
  'love',
  'marriage',
  'medieval',
  'mental',
  'military',
  'momentous',
  'my past',
  'narrative',
  'news story',
  'noted',
  'old',
  'old-time',
  'over and done',
  'over',
  'past be the past',
  'past periods',
  'past',
  'pasts',
  'periods prior',
  'politics',
  'power',
  'prescription',
  'previous periods',
  'previous',
  'previously',
  'primeval',
  'primordial',
  'prince',
  'princes',
  'princess',
  'princesses',
  'prior period',
  'prior-period',
  'queen',
  'queens',
  'real',
  'recent',
  'record',
  'recorded in history',
  'recorded',
  'recounted',
  'registered',
  'relevant',
  'reliable',
  'religion',
  'religious',
  'renaissance',
  'retrospective look',
  'scheduled',
  'sequential',
  'significant',
  'spiritual',
  'stored',
  'stories',
  'story',
  'storylike',
  'stroy',
  'summarized',
  'summed',
  'tabled',
  'tale',
  'tallied',
  'their history',
  'this story',
  'throughout history',
  'throughout the history',
  'time past',
  'time',
  'timeline',
  'totaled',
  'traditional',
  'traditionally',
  'travel',
  'true',
  'university',
  'verifiable',
  'version',
  'voyage',
  'war',
  'way back when',
  'wedding',
  'whole',
  'women',
  'working',
  'years past',
  'years',
  'yesteryear',
  'yore',
  'your story',
  'youth'
];
